### ISSUE TITLE
Missing tick property

### ISSUE THREAD

**Issue by Benny-** [Workiva/w_common#79]
The timer interface of Dart 2.0.0 has a new getter. [The tick getter](https://github.com/dart-lang/sdk/blob/bdc6e9c862d5870b9998470e5d856f42bada65cf/sdk/lib/async/timer.dart#L95-L108).

This means the following needs to be added to the `_ObservableTimer` class (which inherits from `Timer`) in `disposable.dart` for it to compile on dart 2 :
```dart
  @override
  int get tick
  {
    return _timer.tick;
  }
```

**Comment by georgelesica-wf** [comment]
Pretty sure this has been resolved.
